Session6
ankita1696/NamasteReact pull request #6
Opened 2022-12-11 19:44 UTC by ankita1696

2022-12-12 06:14 UTC, rasika260896 approved these changes

2022-12-14 12:40 UTC, Pujarini requested changes

2022-12-14 12:40 UTC, Pujarini commented on src/Components/SearchBar.js
>      <div className="wrapper_search">
follow BEM convention

2022-12-14 12:40 UTC, Pujarini commented on src/Components/Team/Team.js
> +      <SearchBar
Write it as a JSX component with no expectation of children.

2022-12-26 17:31 UTC, merged